quarkus.http.port=8085

quarkus.index-dependency.shared-quarkus.artifact-id=shared-quarkus
quarkus.index-dependency.shared-quarkus.group-id=es.upsa.dasi

quarkus.index-dependency.domain.group-id=es.upsa.dasi
quarkus.index-dependency.domain.artifact-id=domain

microprofile.rest.client.disable.default.mapper=true